# Defines the executables to be built
APPLICATIONS = intset_hs intset_ll intset_rb intset_sl 
# Defines which objects belong to 'intset'
intset_hs_OBJS = intset_hs.bc
intset_ll_OBJS = intset_ll.bc
intset_rb_OBJS = intset_rb.bc
intset_sl_OBJS = intset_sl.bc

include ../Makefile.common
