# Defines the executables to be built
APPLICATIONS = counter counter-serial counter-nesting
# Defines which objects belong to each application 
counter_OBJS = counter.bc
counter-serial_OBJS = counter-serial.bc
counter-nesting_OBJS = counter-nesting.bc

include ../Makefile.common

